- devtools/conda-envs/test_env.yaml
- modelforge/tests/test_zenodo.py
- modelforge/utils/__init__.py
- modelforge/utils/zenodo.py
This PR provides a set of functions that will take a zenodo DOI (or zenodo record id) and return the direct link to the associated datafiles (e.g., the gzipped hdf5 files).  
Currently 3 functions have been defined:
* `fetch_url_from_doi` -- for a given DOI, return the associated URL
* `get_zenodo_datafiles` -- for a given zenodo record_id, return all datafiles that match a given file extension
* `hdf5_from_zenodo` -- a wrapper that will return a list of the .hdf5.gz files for a given DOI or record_id
The `hdf5_from_zenodo` function can accept either a zenodo DOI or zenodo record id; additionally, the code will sanitize the input if either of those are passed as urls.  For example, all of the following are equally valid (and in this case equivalent):
```
files = …
```
> Zenodo loader

- modelforge/curation/qm9_curation.py
- modelforge/curation/spice_openff_curation.py
- modelforge/tests/test_curation.py
Reference energy (i.e., energy of the constituent atoms in vacuum) is computed for the QM9 dataset from the data made available in the paper SI; other thermochemical properties calculated and added to the datafile, reference energy at 298.15K, reference enthalpy at 298.15K and reference free energy at 298.15K.    This formation energy is also calculated and added to the data files for 0K (i.e., internal energy - reference energy).
equivalent shifted enthalpy, free energy, and internal energy at 298.15K could also be calculated, but given the very close similarity to internal energy at 0K (and the fact we will be training off internal energy at 0K), I do not think this will be necessary; of course, since the references are provided for each of these, they could be calculated by a user
> Added in reference energy calculation for qm9.  

- modelforge/curation/ani1x_curation.py
- modelforge/curation/curation_baseclass.py
- modelforge/curation/qm9_curation.py
- modelforge/curation/spice_curation.py
- modelforge/curation/spice_openff_curation.py
The doc strings  related  to the "format" (i.e., series_mol, series_atom) stuff, wasn't fully updated. 
This fixes up those docstrings
> Fixing a minor issues with docstrings in curation

- modelforge/potential/models.py
- modelforge/potential/painn.py
- modelforge/potential/schnet.py
- modelforge/potential/utils.py
- modelforge/tests/helper_functions.py
- modelforge/tests/test_utils.py
Input dimensions for `inputs["atomic_numbers"]` has shape (nr_of_atoms_in_batch, 1), which was flattended in the `BaseNNP` before. Now we keep dimensions and let the NNP decide what to do with it.
Should we change the name of the input property `atomic_number` 
https://github.com/choderalab/modelforge/blob/6dab8a1a376a8b0cf83d84ac927793154239e272/modelforge/potential/models.py#L172
to `atomic_properties`? The way we are approaching the embedding in this PR makes it flexible to have other properties defined in this tensor with the now flexible shape `(nr_of_atoms_in_batch, *, *)`. What do you think @ArnNag ?
> Keep input dimensions consisten

- devtools/conda-envs/test_env.yaml
- modelforge/dataset/dataset.py
- modelforge/dataset/qm9.py
- modelforge/potential/__init__.py
- modelforge/potential/models.py
- modelforge/potential/painn.py
- modelforge/potential/schnet.py
- modelforge/potential/utils.py
- modelforge/tests/helper_functions.py
- modelforge/tests/test_curation.py
- modelforge/tests/test_models.py
- modelforge/tests/test_nn.py
- modelforge/tests/test_painn.py
- modelforge/tests/test_schnet.py
- modelforge/tests/test_spk.py
- modelforge/tests/test_utils.py
- modelforge/utils/remote.py
- scripts/training.py
Currently, we are not enforcing units at several public interfaces. This PR aims to fix this and enforces the internal use of the openmm unit system. This PR will close issues #54 and #32.
The `forward` call of the models will check for units attached to `positions` and convert them to nanometers if possible. If no units are attached, it will assume that the units are in nanometers and print a warning to stderr.
> Adding unit checks to the public API

- modelforge/dataset/qm9.py
- modelforge/dataset/utils.py
Hosting test data on gdrive was a quick solution initially, but it became difficult to maintain and unstable.
This PR switches to gh lfs.
> switching from gdrive to gh lfs

- devtools/conda-envs/test_env.yaml
- modelforge/curation/curation_baseclass.py
- modelforge/dataset/dataset.py
- modelforge/dataset/qm9.py
- modelforge/dataset/transformation.py
- modelforge/dataset/utils.py
- modelforge/potential/__init__.py
- modelforge/potential/models.py
- modelforge/potential/painn.py
- modelforge/potential/postprocessing.py
- modelforge/potential/schnet.py
- modelforge/potential/utils.py
- modelforge/tests/helper_functions.py
- modelforge/tests/test_curation.py
- modelforge/tests/test_dataset.py
- modelforge/tests/test_models.py
- modelforge/tests/test_nn.py
- modelforge/tests/test_painn.py
- modelforge/tests/test_schnet.py
- modelforge/tests/test_spk.py
- modelforge/tests/test_training.py
- modelforge/tests/test_utils.py
- modelforge/utils/misc.py
- modelforge/utils/units.py
- scripts/training.py
It is common in training neural network potentials to perform pre-processing steps on the energies used for training. 
Two common strategies are (described in more detail here https://doi.org/10.1063/5.0160326):
- offsetting the molecular energies by the atomize energies (self energies of the free atoms in vacuum) to avoid numerical instability with the typical considerable total energies
- scaling the range of energies to a unit interval
Both pre-processing strategies require information passed from the dataset to the model, since the transformations must be reversed to obtain total energies.
This PR adds functionality to the dataset class to offset the total energies using atomic self-energies, calculated or provided for a specific level of theory and dataset, as well as the mean and …
> Pre-processing dataset energies

- modelforge/potential/models.py
- modelforge/potential/schnet.py
- modelforge/potential/utils.py
- modelforge/tests/test_ani.py
- modelforge/tests/test_nn.py
- modelforge/tests/test_spk.py
- modelforge/tests/test_utils.py
Small refactoring changes to the structure of SchNet and the way the Cosine Cutoff is applied to the radial basis functions. This also impacts the feature aggregation. While making these changes, I noticed that we haven't had a useful unit test for the radial basis function class; I added this here now.
For reference (I will also add this to the documentation):
displacement vectors (`r_ij`) have shape (nr_of_atoms, 3)
distances (`d_ij`) have shape (nr_of_atoms, 1)
radial basis function (`f_ij`) have shape (nr_of_atoms, 1, number_of_gaussian)
cutoff has shape (nr_of_atoms, 1)
> Refactor SchNet potential module and add unit test for radial basis functions

- modelforge/tests/helper_functions.py
Updated the equivariance_test_utils in helper_functions to set a seed before calling a random translation to ensure the same test regardless of the sequence of calls prior.  This addresses issue #82 . 
This test was failing to meet the tolerance (for values close to zero) depending on the order called because  the translation tensor was generated via torch.randn.  I just added in a manual setting of a seed to ensure we are doing the same translation each time to avoid this test potentially failing as we add new tests/models to test.
> update equivariance test

- modelforge/potential/ani.py
Torchani used atom index instead of atomic numbers to aggregate the element specific atomic contributions. Sidenote: we should standardize this between the NNPs at some point, and always use atomic numbers for index operations.
> fix indexing bug

- modelforge/potential/__init__.py
- modelforge/potential/models.py
- modelforge/tests/conftest.py
- modelforge/tests/test_models.py
- modelforge/tests/test_training.py
- modelforge/train/training.py
We are using a TrainingAdaptor to train neural network potentials (the Pytorch NNP model is an attribute of the TrainingAdaptor, which inherits from Pytorch-Lightning). When we serialize the state_dict, this is reflected in the keys, which are prefixed by `model.`. When we generate a model for inference, we don't use it with the TrainingAdapter, but the vanilla NNP (without any overhead from PyTorch-Lightning). To load a state dictionary correctly, we need to remove the `model.` prefix for each of the state_dict keys.
This PR overrides the native `load_state_dict` and adds a preprocessing step before calling `super().load_state_dict` to remove the `model.` prefix if found in the keys of the state_dict.
> State Dictionary saving/loading

- modelforge/potential/models.py
- modelforge/potential/utils.py
- modelforge/tests/test_ani.py
- modelforge/tests/test_models.py
- modelforge/tests/test_spk.py
The data loader provides the input for each neural network as a data class. This PR adds methods to consistently cast each of the tensors to `device` and `dtype`, analogous to the model casting.
> Allow consistent `dtype` and `device` casting of models and input parameters

- modelforge/dataset/qm9.py
- modelforge/potential/__init__.py
- modelforge/potential/ani.py
- modelforge/potential/models.py
- modelforge/potential/painn.py
- modelforge/potential/physnet.py
- modelforge/potential/processing.py
- modelforge/potential/sake.py
- modelforge/potential/schnet.py
- modelforge/potential/utils.py
- modelforge/tests/test_ani.py
- modelforge/tests/test_painn.py
- modelforge/tests/test_sake.py
- modelforge/tests/test_spk.py
- modelforge/tests/test_training.py
- modelforge/tests/test_utils.py
Previously, we have implemented all base functionality, including the neighbor list calculation, in a base class from which each neural network inherits. While this was straightforward, this abstraction made exporting the model and exchanging the neighbor list calculation difficult.
To make these use cases work, the new structure is as follows (outlined for ANI):
`ANI2x` class that wraps and initializes `ANI2xCore` and `InputPreparation` instances. The `InputPreparation` class takes cartesian coordinates as input and outputs `d_ij` and `r_ij`, as well as neighbor indices. The `ANI2Core` performs all calculations necessary for the neural network operating on the output of the `InputPreparation`.
When models are exported, only the `Core` class is exported.
> Refactor base class for neural network potentials

- modelforge/dataset/dataset.py
- modelforge/dataset/utils.py
Further speed up to _subtract_self_energies in DataModule by directly indexing into the atomic_numbers tensor to avoid additional overhead.  Reduces
As further described in Issue #120 , the overhead of `__getitem__` seems to be an additional factor.  We only are using the atomic numbers, so all the other data returned when indexing into the dataset are not needing and just slowing things down.  I just directly indexed into the tensor to get the relevant atomic numbers, and that seems to give some further substantial speed ups (reducing cost about ~50%).  Update: Overlooked that I was using the getter to retrieve energy.  Speed up is even better (see timings below). 
This will additionally address issue #124, swapping in np.cumsum for torch._utils._accumulate in the record splitting …
> Further speed up to _subtract_self_energies 

- modelforge/dataset/dataset.py
- modelforge/tests/conftest.py
- modelforge/tests/test_dataset.py
- modelforge/tests/test_models.py
- modelforge/tests/test_painn.py
- modelforge/tests/test_physnet.py
- modelforge/tests/test_pt_lightning.py
- modelforge/tests/test_sake.py
- modelforge/tests/test_schnet.py
- modelforge/tests/test_training.py
We have accumulated technical debts in the configuration of some of our tests. This PR is a first attempt to clean up the overuse of slightly similar but different fixtures, for which the control flow is hidden in `conftest.py,` making it sometimes difficult to understand what is done in a particular test.
I opted for explicitly passing control parameters to each test instead of hiding these in fixtures. I have cleaned up some of the fixtures and simplified them where appropriate. We still use fixtures to set up datasets/databases/database containers. (Sidenote: In one of the next PRs, we need to address the inflationary use of the word dataset in the classes --- it is challenging to distinguish between some of the concepts without reading the documentation.)
> Addressing overuse of fixtures

- modelforge/dataset/dataset.py
- modelforge/potential/__init__.py
- modelforge/potential/models.py
- modelforge/potential/utils.py
- modelforge/tests/test_dataset.py
- modelforge/tests/test_training.py
- modelforge/train/training.py
Tests still need to cover the Loss functions used in the training routine, this PR addresses this.
This PR also adds forces to the getter method of the `TorchDataset` and the `collateconformers` method, as raised here: #127 . It also improves performance by casting dtype on the full tensor and not on individual tensor slices.
> Adapt training for forces

- modelforge/dataset/dataset.py
I was making a wrong assumption about the PyTorch dataset class's default behavior, which does not shuffle by default. This PR sets `shuffle=True` for the training set.
> Bugfix: training set was not shuffled at each epoch

- modelforge/potential/models.py
- setup.py
This relates to issue #134 .  Basically, the initial code allocated tensors of size (n*(n-1)) in the process of identifying particle pairs, where n is the total number of atoms in all the molecules. After these pairs are enumerate, they were filtered by whether or not they are in the same molecule.  For larger datasets, this allocates large arrays, which were too large for me to run locally or on the readily available 2080s.   
To address this, I just wrapped the same basic code in a for loop, so we are instead allocating tensors of size (n-1), and just performing the calculation n times, effectively reducing memory allocation by a factor of n.  In each iteration of the loop, we do the filtering by whether pairs are on the same molecule and accumulate those pairs.  
As noted in the issue, …
> Refactoring pairs calculation to be more memory efficient.

- modelforge/dataset/yaml_files/spice2.yaml
- modelforge/tests/conftest.py
- modelforge/tests/pytest.ini
- modelforge/tests/test_dataset_downloads.py
- scripts/perform_training.py
Added in test to check dataset download.  The tests will be skipped ( only will run if --run_data_download is passed to the CLI).  This test will take a lot of time so I'm sure this is not something we would want to do with any frequency. It might be worth creating separate tests (instead of parameterize) to make it easier to just specifically test a given dataset. 
It might also be better to make this NOT a pytest test and just a separate piece of code that gives more options to check/test very specific datasets and versions and give more descriptive outputs.  Having something like that in the dataset module, where people can more easily query available datasets and versions.
> Fixed error in spice2.yaml file.  

- modelforge/potential/ani.py
- modelforge/potential/models.py
- modelforge/potential/painn.py
- modelforge/potential/physnet.py
- modelforge/potential/sake.py
- modelforge/potential/schnet.py
- modelforge/potential/tensornet.py
The `CoreNetwork` constructor has an unused parameter named `cutoff`. This PR removes this parameter from the constructor signature and all calls to it.
> Remove unused cutoff parameter

- .github/workflows/CI.yaml
- modelforge/dataset/dataset.py
- modelforge/potential/models.py
- modelforge/potential/processing.py
- modelforge/potential/utils.py
- modelforge/tests/conftest.py
- modelforge/tests/test_ani.py
- modelforge/tests/test_dataset.py
- modelforge/tests/test_dataset_downloads.py
- modelforge/tests/test_models.py
- modelforge/tests/test_painn.py
- modelforge/tests/test_physnet.py
- modelforge/tests/test_sake.py
- modelforge/tests/test_schnet.py
- modelforge/tests/test_training.py
- setup.py
As discussed in issue #141 training takes too long and spends most of the compute time generating the pairlist. To move this from a per-epoch cost to a one-time cost this PR moves the calculation of the pairlist to the dataset and saves the pairlist. 
The pairlist is then passed, as an optional parameter, as input to the network. The Neighborlist class takes it as optional input and calculates distances to further filter it to the local neighborhood for each atom within a cutoff.
> Splitting pairlist and neighborlist calculation

- modelforge/dataset/dataset.py
- modelforge/potential/processing.py
- modelforge/tests/test_dataset.py
- modelforge/tests/test_models.py
Instead of padding the pair list to generate an (M,N,2) tensor with M number of molecules, N maximum number of pairs in the dataset, and 2 the pairlist dimension we can generate a (K,2) tensor with K as the total number of atom pairs in the dataset. This requires keeping track of index arrays to correctly retrieve atom pairs for a molecule.
> Refactor pairlist representation

- modelforge/dataset/dataset.py
- modelforge/potential/models.py
- modelforge/tests/test_dataset.py
This PR makes sure that the ANI model reduces a pairlist/neighborlist with redundant atom pairs (i.e., atom indices for the pair atom 1 and atom 2 are ((1,2),(2,1))). For ANI, we require non-redudant atom pairs. 
There are multiple points where the different pairlist could be implemented. 
I opted for:
(1) a keyword provided to the dataset generation that controls whether to include redundant pairs or not
(2) inside the ANI model an additional indexing step that will reduce a redundant to a non redundant pairlist
> Ref ani neighborlist

- modelforge/train/training.py
For training, we often want to modify either the dataset or the potential, and keep the training config fixed. To avoid having multiple config files with the exact same entries for dataset/potential and training, this PR allows us to use separate config files for potential/dataset/training.
> Training script accepts multiple config files

- modelforge/dataset/dataset.py
- modelforge/potential/models.py
- modelforge/tests/test_models.py
As mentioned in #151 the largest datasets start to bog down in the pre-calculation of the pair list.  
Switching to a numpy-based function that operates on batches provides substantial speed improvements. I do use the torch DataLoader, with shuffle=False, so the order will be preserved for constructing the pair tensor and indexing tensors.  
In the prior version of the code, processing spice114 took about 13 minutes to generate the pair list and remove self energies.   This code now takes about 70 seconds for both operations. 
Marcus reported this step took roughly 40 minutes for these steps with ani2x, it now is about 4 minutes for the removing of self-energies and about 3 minutes for the pair list pre-computation.
Based on some experimentation, it seems like a batch size of 500 and 4 …
> Pair list enumeration speed improvements

- devtools/conda-envs/doc_env.yaml
- devtools/conda-envs/test_env.yaml
- devtools/conda-envs/test_env_mac.yaml
- modelforge/dataset/utils.py
- modelforge/potential/ani.py
- modelforge/potential/models.py
- modelforge/potential/painn.py
- modelforge/potential/physnet.py
- modelforge/potential/schnet.py
- modelforge/potential/utils.py
- modelforge/tests/data/training_defaults/default.toml
- modelforge/tests/test_painn.py
- modelforge/tests/test_training.py
- modelforge/tests/test_utils.py
- modelforge/train/training.py
We have used `scatter_sum` instead of `Tensor.scatter_add_`. The `scatter_sum` operation from `pyg` performs tensor initialization to store the sum, broadcasting and other operations (setting dtype, device) under the hood. In some cases, this can lead to unexpected behavior. The main reason for the move to the native scatter operations is the need to install a separate package, `torch_scatter,`, which leads to a larger dependencies graph.
> Remove pyg dependency

- modelforge/potential/ani.py
- modelforge/potential/models.py
- modelforge/potential/painn.py
- modelforge/potential/physnet.py
- modelforge/potential/sake.py
- modelforge/potential/schnet.py
I noticed that each model includes the initialization of the `InputPreparation` class  (which handles the calculation of the neighborlist and pairwise distances) in its implementation. The better location for this initialization is the super class (`BaseNetwork`).
> Moving call to input preparation to BaseNetwork

- modelforge/potential/utils.py
As @ArnNag noticed, the `Dense` implementation was inconsistent in how weights and biases are initialized vs how these are reset. During initialization and resetting, the implementation used different distributions to draw values.
> fix inconsistency in weight/bias initialization

- modelforge/dataset/utils.py
- modelforge/potential/ani.py
- modelforge/potential/models.py
- modelforge/potential/painn.py
- modelforge/potential/parameters.py
- modelforge/potential/physnet.py
- modelforge/potential/sake.py
- modelforge/potential/schnet.py
- modelforge/potential/tensornet.py
- modelforge/potential/utils.py
- modelforge/tests/data/potential_defaults/ani2x.toml
- modelforge/tests/data/potential_defaults/painn.toml
- modelforge/tests/data/potential_defaults/physnet.toml
- modelforge/tests/data/potential_defaults/sake.toml
- modelforge/tests/data/potential_defaults/schnet.toml
- modelforge/tests/test_ani.py
- modelforge/tests/test_painn.py
- modelforge/tests/test_sake.py
- modelforge/tests/test_schnet.py
- modelforge/tests/test_spk.py
- modelforge/tests/test_utils.py
- scripts/config.toml
This PR makes the following small naming changes:
- instead of `max_Z` for the highest element that defines the vocabulary for the embedding we use `highest_atomic_number`.
- instead of `cutoff` indicating the maximum interaction distance we use `maximum_interaction_radius`. This change is because some networks also define a minimum length, and the naming of that value was awkward, but `minimum_interaction_radius` is verbose and clear.
Additionally, to be more flexible, this PR includes changes allowing the user to define the activation function in the toml file. This clarifies what activation function is used and allows for rapid change. This won't work for all models out of the box; e.g., ANI uses the `CeLU` activation function with a defined alpha value. 
Some smaller changes include …
> Smaller refactoring changes

- modelforge/potential/parameters.py
The field validator for validating and converting str to units was defined twice in the tensornet model.  This was modified such that the two fields to validated are passed to the same validator definition (rather than defining it a second time with two different names).
> quick updated to tensornet pydantic model

- modelforge/tests/data/runtime_defaults/runtime.toml
- modelforge/train/parameters.py
save_idr parameter was both defined in the runtime and training.toml, and only the runtime.toml parameter was used, but the Pydantic model also expected it to present the runtime.toml (without any additional effect).
> fix conflicting save_dir parameter definition

- modelforge/dataset/dataset.py
- modelforge/tests/conftest.py
- modelforge/tests/test_models.py
- modelforge/utils/misc.py
Move the functions to test on a single batch of dataset from the test folder to the modelforge folder, makes it easier to use in notebooks/scripts and avoids duplication.
> Make it easier to test on single batch of dataset

- modelforge/dataset/dataset.py
- modelforge/potential/models.py
- modelforge/potential/parameters.py
- modelforge/potential/processing.py
- modelforge/tests/data/potential_defaults/ani2x.toml
- modelforge/tests/data/potential_defaults/painn.toml
- modelforge/tests/data/potential_defaults/physnet.toml
- modelforge/tests/data/potential_defaults/sake.toml
- modelforge/tests/data/potential_defaults/schnet.toml
- modelforge/tests/data/potential_defaults/tensornet.toml
- modelforge/tests/test_models.py
This PR implements one strategy to perform charge conservation. it implements the infrastructure to swap the strategy against others in the future, and adds the necessary control parameter in the TOML/Pydantic model.
> Charge conservation

- .github/workflows/CI.yaml
- devtools/conda-envs/test_env.yaml
- devtools/conda-envs/test_env_mac.yaml
- modelforge/dataset/dataset.py
- modelforge/dataset/phalkethoh.py
- modelforge/tests/conftest.py
- modelforge/tests/test_aimnet2.py
- modelforge/tests/test_curation.py
- modelforge/tests/test_dataset.py
- modelforge/tests/test_models.py
- modelforge/tests/test_nn.py
- modelforge/tests/test_painn.py
- modelforge/tests/test_physnet.py
- modelforge/tests/test_pt_lightning.py
- modelforge/tests/test_remote.py
- modelforge/tests/test_sake.py
- modelforge/tests/test_tensornet.py
- modelforge/tests/test_training.py
- modelforge/tests/test_utils.py
The CI is taking quite a long time to run (about 45 minutes).  This aims to speed this up using pytest-xdist, which will allow concurrent execution of tests.  To do this though, we need to make sure our tests will not be in conflict (make sure any files being written out/read have unique names, making sure all unique test files are at minimum using their own unique temp directories). 
Edit: actual numbers from the last merge into main:
- ubuntu 3.11: 44m 16s
- ubtuntu 3.10: 44m 23s
- macOS 3.11: 53m 30s
- macOS 3.10: 48m 42s
> Speeding up CI using pytest-xdist

- docs/getting_started.rst
- docs/training.rst
- modelforge/dataset/dataset.py
- modelforge/potential/ani.py
- modelforge/potential/painn.py
- modelforge/potential/physnet.py
- modelforge/potential/potential.py
- modelforge/potential/representation.py
- modelforge/potential/schnet.py
- modelforge/tests/data/config.toml
- modelforge/tests/data/training_defaults/default.toml
- modelforge/tests/test_parameter_models.py
- modelforge/tests/test_training.py
- modelforge/train/losses.py
- modelforge/train/parameters.py
- modelforge/train/training.py
- modelforge/utils/prop.py
- scripts/config.toml
This PR includes only refactoring changes from PR #266 and #281 . PR #266 will need more time to finish documentation and #266 can be closed after this.
> cherry picked changes from other PRs

- modelforge/dataset/__init__.py
- modelforge/jax.py
- modelforge/potential/ani.py
- modelforge/potential/featurization.py
- modelforge/potential/neighbors.py
- modelforge/potential/painn.py
- modelforge/potential/physnet.py
- modelforge/potential/potential.py
- modelforge/potential/sake.py
- modelforge/potential/schnet.py
- modelforge/potential/tensornet.py
- modelforge/potential/utils.py
- modelforge/tests/conftest.py
- modelforge/tests/precalculated_values.py
- modelforge/tests/test_ani.py
- modelforge/tests/test_dataset.py
- modelforge/tests/test_potentials.py
- modelforge/utils/prop.py
When changing NNPInput from a tuple to using slots, pair_list and per atom charge were set to None.  While we can call torch.jit.script on the potential with None in the NNPInput and evaluate it, we can't write it to file as it goes through all the validation.  
This defines these as empty tensors; we can check the shape of the pair_list in the Neighborlist to know if we need to generate these pairs.
> Fixing NNPInput to allow us to write torch script models

- modelforge/dataset/ani1x.py
- modelforge/dataset/ani2x.py
- modelforge/dataset/dataset.py
- modelforge/dataset/phalkethoh.py
- modelforge/dataset/qm9.py
- modelforge/dataset/spice1.py
- modelforge/dataset/spice1openff.py
- modelforge/dataset/spice2.py
- modelforge/potential/potential.py
- modelforge/tests/test_dataset.py
- modelforge/train/training.py
- modelforge/utils/prop.py
This address the issue related to the force units being off (per angstrom, not per nanometer) in the datasets. 
- #298
> refactoring HDF5Dataset class to check and convert units.

- modelforge/train/training.py
This PR adds logging for epoch time. The time is measured as wall time between  `on_train_epoch_start` and `on_train_epoch_end` method calls.
> log time per epoch

- modelforge/train/training.py
This PR addresses an issue introduced in PR #308 where logging of the epoch time was intended to occur only on the main process (rank == 0). However, this led to a synchronization error that caused training to freeze after the first epoch. To resolve this, we adjusted the logging to ensure it only occurs on the main process without disrupting the training flow.
- Adjusted Logging Conditions: Updated specific logging calls to include rank_zero_only=True where necessary. This change ensures that logging occurs only on the main process without causing synchronization issues across processes.
- Removed Redundant Logging Checks: Refactored the logging of certain metrics to avoid redundant if self.global_rank == 0 checks by using rank_zero_only directly in self.log() calls.
- Ensured Sync …
> Dev global rank

- .github/workflows/CI.yaml
- .github/workflows/black.yml
- devtools/conda-envs/test_env.yaml
- devtools/conda-envs/test_env_mac.yaml
- docs/inference.rst
- modelforge/potential/potential.py
- modelforge/tests/test_potentials.py
- modelforge/tests/test_remote.py
- scripts/modify_state_dict.py
It would be convenient to be able to setup a potential directly from a checkpoint file on weights and biases.  This PR implements such functionality.
> Load a checkpoint file from wandb directly into a potential.

- modelforge/dataset/phalkethoh.py
- modelforge/train/parameters.py
- modelforge/train/training.py
Provide a brief description of the PR's purpose here.
> Add training parameter "profiler"

- modelforge/potential/neighbors.py
A debug statement was left in as part of the tmqm dataset PR. This just removes these two print statements.
> removed a debugging statement from neighbors.py

- docs/datasets.rst
- docs/getting_started.rst
- modelforge/curation/scripts/curate_spice114_openff.py
- modelforge/curation/spice_1_openff_curation.py
- modelforge/dataset/dataset.py
- modelforge/dataset/parameters.py
- modelforge/dataset/yaml_files/spice1openff.yaml
- modelforge/potential/parameters.py
- modelforge/tests/data/config.toml
- modelforge/tests/data/dataset_defaults/ani1x.toml
- modelforge/tests/data/dataset_defaults/ani2x.toml
- modelforge/tests/data/dataset_defaults/phalkethoh.toml
- modelforge/tests/data/dataset_defaults/qm9.toml
- modelforge/tests/data/dataset_defaults/spice1.toml
- modelforge/tests/data/dataset_defaults/spice1_openff.toml
- modelforge/tests/data/dataset_defaults/spice2.toml
- modelforge/tests/data/dataset_defaults/tmqm.toml
- modelforge/tests/test_dataset.py
- modelforge/tests/test_parameter_models.py
- modelforge/train/training.py
This provides changes aimed at improving the control over datasets.  Specifically, the switch to .toml files meant we could not easily toggle which properties to load from the hdf5 files nor which properties to assign to the key internal variables (energy, force, dipole_moment, etc.). 
This updates the pydantic dataset model whereby users now additionally define properties of interest (as a list) and then the association of these properties to the internal variable names (i.e used by the `Properties` class).  The pydantic model validates that anything in the Properties association also exists in the properties_of_interest list.   We do not validate that the properties_of_interest are actually in the hdf5 file via the pydantic model; this is handled when we assign those parameters while …
> Improved dataset control

- modelforge/curation/scripts/limit_tmqm.py
- modelforge/dataset/yaml_files/tmqm.yaml
Provide 4 additional subsets of the tmqm dataset
various subsets:
- Pd, Zn, Fe, Cu: 27685 molecules
- Pd, Zn, Fe, Cu and then exclude any molecules that contain elements not in the set: C, H, P, S, O, N, F, Cl, Br: 18515 molecules
- Pd, Zn, Fe, Cu, Ni, Pt, Ir, Rh, Cr, Ag: 60637 molecules
- Pd, Zn, Fe, Cu, Ni, Pt, Ir, Rh, Cr, Ag and then exclude any molecules that contain elements not in the set: C, H, P, S, O, N, F, Cl, Br: 40866 molecules
> Adding additional versions of tmqm.

- .github/workflows/CI.yaml
- modelforge/tests/test_training.py
This PR is focused on trying different strategies to speed up our CI testing. 
One issue is that the training tests are very memory intensive and only a single can be run at a time.  I've tried putting these into a single xdist group (which will mean they will all execute on the same worker thus multiple will not be running at the same time); I've upped the number of workers to 4, since many of the other tests are not memory intensive (or cpu intensive), and can more can easily run concurrently. 
this drops CI testing from 43 minutes to 23 minutes.
> Improving speed of CI testing
