choderalab/modelforge

devtools/conda-envs/test_env.yaml, modelforge/dataset/__init__.py, modelforge/dataset/dataset.py, modelforge/dataset/qcarchive.py, modelforge/dataset/qcdataset.py, modelforge/dataset/qm9.py, modelforge/dataset/utils.py, modelforge/potential/min_operations.py, modelforge/tests/test_dataset.py, modelforge/tests/test_modelforge.py
Outline the basic dataset structure
This PR contains the structure for a `BaseDataset` that inherits from `torch.utils.data.Dataset` and contains functions to retrieve, manipulate and cache the downloaded dataset.
It also contains an implementation of a `QM9Dataset` that  provides functions that control from which remote location the dataset is retrieved and the transformations to generate an opimized npy file. It also implements the `__getitem__` and `__len__` calls necessary for the   `torch.utils.data.Dataset` class.
=> Initial dataset structure

devtools/conda-envs/test_env.yaml, modelforge/dataset/dataset.py, modelforge/dataset/qm9.py, modelforge/dataset/transformation.py, modelforge/dataset/utils.py, modelforge/tests/test_dataset.py
Provides a dataset implementation that can be used for most of the QM Datasets provided generated from the QCArchive and provided as HDF5file.
For a specific dataset (e.g. QM9) generating a dataset is as easy as:
```
factory = DatasetFactory()
prop = QM9Dataset()
dataset = factory.create_dataset(prop)
```
and the dataset provides Pytorch `Dataloader` for a default data split (random split, 80:10:10).
The split can be stored and reproduced using `dataset.store_split(filename)` and `dataset.restore_split(filename`.
The `DatasetFactory()` will first check if there the dataset is already  cached on disk, if not it will download the dataset specified in `prop` and generate a local cache. The local cache is a npy file. Padding is performed by the  `PadTensors` class. 
Currently only the …
=> Initial structure for datasets

.github/workflows/CI.yaml, devtools/conda-envs/test_env.yaml
Just a few CI improvements, let me know if you have any questions!
=> CI Tweaks 

modelforge/potential/schnet.py
Split the representation and interaction block in the SchNET implementation.
=> split representation and interaction block

modelforge/potential/__initi__.py, modelforge/potential/models.py, modelforge/potential/pain.py, modelforge/potential/schnet.py, modelforge/potential/utils.py, modelforge/tests/helper_functinos.py, modelforge/tests/helper_functions.py, modelforge/tests/test_dataset.py, modelforge/tests/test_models.py, modelforge/tests/test_painn.py, modelforge/tests/test_remote.py, modelforge/tests/test_schnet.py, modelforge/tests/test_training.py, modelforge/tests/test_utils.py
THis PR fixes a bug in the padding of the embedding and interaction layer of SchNET.
=> Fixed dim issue with SchNET implementation

.gitignore, modelforge/potential/models.py, modelforge/potential/pain.py, modelforge/potential/schnet.py, modelforge/tests/helper_functions.py, modelforge/tests/test_models.py, modelforge/tests/test_painn.py, modelforge/tests/test_schnet.py
Passing emedding to the model constructor
=> Pass embedding to model constructor

modelforge/dataset/dataset.py, modelforge/dataset/utils.py, modelforge/tests/test_dataset.py
=> Shuffle by record rather than conformer 

modelforge/potential/__init__.py, modelforge/potential/models.py, modelforge/potential/utils.py, modelforge/tests/helper_functions.py, modelforge/tests/test_models.py, modelforge/tests/test_nn.py, modelforge/tests/test_spk.py, modelforge/tests/test_utils.py, scripts/training.py
Due to the rapid and asynchronous development in this repo PR #64 and #55 have introduced merge conflicts that were difficult to fix. This PR consolidates these in a single PR that updates the `main` branch.
=> Refactoring and solving merge conflicts

modelforge/potential/ani.py, modelforge/potential/models.py, modelforge/potential/schnet.py, modelforge/potential/utils.py, modelforge/tests/test_ani.py
Adoption of cutoff and scaling constants in Radial/Angular symmetry functions.
=> Small refactoring to match the ANI2x radial/angular symmetry function output

modelforge/potential/ani.py, modelforge/potential/models.py, modelforge/potential/painn.py, modelforge/potential/physnet.py, modelforge/potential/schnet.py, modelforge/potential/utils.py, modelforge/tests/test_ani.py, modelforge/train/tuning.py
As we move to datasets that include per-atom forces, the loss function needs to be adopted.
=> Include forces in loss function

modelforge/dataset/dataset.py, modelforge/potential/ani.py, modelforge/potential/utils.py, modelforge/tests/test_dataset.py
Bugfix for the ANI-2x implementation, addressing issue #96
=> removed elements not implemented from ATOMIC_NUMBER_TO_INDEX_MAP

modelforge/potential/sake.py
=> Update SAKE pairlist indices

modelforge/potential/ani.py, modelforge/potential/tensornet.py, modelforge/tests/test_tensornet.py
NNPInput has been moved to modelforge/modelforge/potential/utils.py, while an import line in ani.py remains un-updated (imported from modelforge/modelforge/potential/models.py).
=> import NNPInput typo

modelforge/potential/schnet.py
The `torch_scatter` utility allows for more readable code; I have updated the SchNet convolution calculation using the function.
=> Use scatter_add instead of torch.scatter_add

modelforge/dataset/dataset.py
This PR provides improved efficiency of the `_subtract_self_energies` function in the `DataModule` (in dataset.py).  As mentioned in issue #120, this step was prohibitively expensive for large datasets (2.5 hours on my laptop for ANI2X, over 3 hours on the lilac cluster).  This is a simple fix that stores molecule self energy in a dictionary,  so we do not need to recompute for each conformer of a molecule.   The dictionary key for this is the concatenation of the atomic numbers into a string (separated by spaces); this does not differentiate between different molecules with the same atoms in the same order (but different structures), which is fine, because our calculation of the self energy is just the sum of atomic self energies and does not consider any other possible aspects of the …
=> Improved the efficiency of the `_subtract_self_energies` function.

modelforge/potential/painn.py, modelforge/potential/physnet.py, modelforge/potential/sake.py, modelforge/potential/schnet.py, modelforge/potential/utils.py, modelforge/train/training.py, scripts/perform_training.py
The title says it all: for each NNP the published values for dimensionality of features space, etc, is set as default values.
=> match original neural network hyperparameters

modelforge/potential/physnet.py
PhysNet's performance significantly deviated from the published results for QM9 and was also far worse than that of the other networks. This PR refactors the network, adds a DropOut layer, and initializes the linear mapping of the residual layers with zeros (as in the original implementation) instead of ones.
These modifications increase the performance and result in a test set RMSE of ~1kcal/mol, which is still not on par with the publisher results but a significant improvement.
=> Refactoring of PhysNet

modelforge/tests/test_training.py, modelforge/train/training.py
Monitoring histograms of bias/weights and parameters during training can provide valuable insights into the training process and model behavior. It helps with detecting vanishing/exploding gradients, monitoring training dynamics and identifying overfitting/improper initialization. 
This PR sets up TensorBoard logging to monitor histograms of weights and biases in PyTorch Lightning.
=> logging weights/biases/parameter histograms for each layer

modelforge/potential/processing.py, notebooks/benchmark.ipynb, scripts/profile_epoch.py, scripts/profile_network.py
Training on larger dataset has high cost associated with each epoch (e.g., ANI2x trained on the ANI2x dataset currently takes ~8h for a single epoch on a GTX 3090). Before committing, we should spend a few days profiling the training pipeline.
=> Profiling scripts for training/inference

modelforge/tests/conftest.py, modelforge/tests/test_models.py
Updated branch with test described in PR #114
=> Ref chemical equi

modelforge/train/training.py
Some models have unused parameters during training (e.g., training ANI2x on QM9 some atomic networks are not trained since the elements are not present). This PR includes code to log the names of the unused parameters after training ends and logs them.
=> Log unused parameters at end of training

modelforge/potential/ani.py, modelforge/tests/test_ani.py, modelforge/train/training.py
Allow proper passing of list of integers from bash script to python. Also, fix a bug that was saving the histogram of the biases&weights after each pass rather than after each training epoch.
This PR also refactors the training script slightly and is more verbose about the parameters that are passed.
=> Bugfix training script

modelforge/potential/schnet.py, modelforge/tests/precalculated_values.py, modelforge/tests/test_ani.py, modelforge/tests/test_painn.py, modelforge/tests/test_physnet.py, modelforge/tests/test_schnet.py
Remove the tensornet dependencies from PhysNet
=> update physnet tests

modelforge/dataset/utils.py, modelforge/potential/ani.py, modelforge/potential/models.py, modelforge/potential/utils.py, modelforge/tests/data/training_defaults/default.toml, modelforge/tests/test_utils.py, modelforge/train/training.py
Splitting strategy control flow was currently buried in the training routine. This exposes these routines and make them accessible through a field in the toml file.
=> move splitting strategy definition to toml file

modelforge/dataset/dataset.py
=> Fix type hint for TorchDataset

modelforge/tests/data/config.toml, modelforge/tests/test_training.py, modelforge/train/training.py, scripts/config.toml
Single toml file loading has been broken, this PR fixes the function.
=> fix bug in loading from single toml

modelforge/dataset/dataset.py, modelforge/potential/__init__.py, modelforge/potential/ani.py, modelforge/potential/painn.py, modelforge/potential/physnet.py, modelforge/potential/schnet.py, modelforge/potential/tensornet.py, modelforge/potential/utils.py, modelforge/tests/data/potential_defaults/painn.toml, modelforge/tests/data/potential_defaults/sake.toml, modelforge/tests/data/potential_defaults/schnet.toml, modelforge/tests/test_ani.py, modelforge/tests/test_nn.py, modelforge/tests/test_tensornet.py, modelforge/tests/test_training.py, modelforge/tests/test_utils.py, modelforge/train/training.py
Refactoring the current training function in a class structure. Additionally, this PR aligns the potential parameters where possible.
=> Put training in class structure

.github/workflows/black.yml, docs/for_developer.rst, modelforge/tests/precalculated_values.py, modelforge/tests/test_modelforge.py, modelforge/tests/test_nn.py, modelforge/tests/test_painn.py, modelforge/tests/test_pt_lightning.py, modelforge/train/training.py
Since the contributor guide indicates we are using the Black formatting style, having a workflow that checks the format of the project source will make reviewing easier.
=> Added Black lint check GitHub Action

modelforge/potential/processing.py, modelforge/tests/test_training.py, modelforge/train/training.py
This PR adds a scaling factor to average over the force error calculated per cartesian coordinate. Also, tests are added for the loss function.
=> Additional scaling factor for force loss (divide by vector length)

modelforge/tests/test_training.py, modelforge/train/training.py
=> fix bug that resulted in force loss without gradient

devtools/conda-envs/env.yaml, pyproject.toml
This PR updates the pyproject.toml project metadata + build system to remove noisy comments, update classifiers, and update tooling information.
=> Cleaning up pyproject.toml

modelforge/potential/__init__.py, modelforge/potential/aimnet2.py, modelforge/potential/parameters.py, modelforge/potential/schnet.py, modelforge/tests/data/potential_defaults/aimnet2.toml, modelforge/tests/test_aimnet2.py, modelforge/tests/test_models.py, modelforge/tests/test_physnet.py
This PR implements a AimNet2-like network
It takes the fork by @ianmkenney and adopts it for the new torchscript architecture.
=> Add AimNet2 architecture

modelforge/tests/test_utils.py, modelforge/utils/misc.py
=> Bugfix lock file

.codecov.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/workflows/CI.yaml, docs/for_developer.rst
This updates the PR template to include a few more check boxes and subsections.  (I just cut and pasted the new template here and am using it for this PR.  Specifically I want to make sure that we are raising issues associated with each PR (even if it is just an enhancement), and put in some checkboxes to remind us to update the .rst files for the documentation.   
This also provides some updates to the contributors guide .rst file to outline the process a bit better
=> Update pr template

devtools/conda-envs/test_env.yaml, devtools/conda-envs/test_env_mac.yaml, modelforge/custom_types.py, modelforge/dataset/dataset.py, modelforge/potential/models.py, modelforge/tests/test_models.py, modelforge/utils/misc.py, modelforge/utils/vis.py
Using torchviz to visualize compute graph. A test is added to generate png model graphs with indicated saved parameters during backward pass.
=> Add function to visualize compute graph of models

devtools/conda-envs/docs_env.yaml, devtools/conda-envs/test_env.yaml, modelforge/potential/models.py, modelforge/tests/test_models.py
=> Skip load_state key modification in training mode

devtools/conda-envs/test_env.yaml, devtools/conda-envs/test_env_mac.yaml
Graphviz was not included in the environment yaml causing CI to fail
=> Ref graphviz

modelforge/train/training.py
This PR addressed the issue described in #279
=> add correct placeholder variable name

modelforge/potential/aimnet2.py, modelforge/potential/ani.py, modelforge/potential/painn.py, modelforge/potential/physnet.py, modelforge/potential/processing.py, modelforge/potential/sake.py, modelforge/potential/schnet.py, modelforge/potential/tensornet.py, modelforge/tests/test_ani.py, modelforge/tests/test_dataset.py, modelforge/tests/test_potentials.py, modelforge/tests/test_utils.py, modelforge/train/training.py
A few changes that are too small for a separate PR are combined here.
=> make dimensions of predicted properties consistent 

modelforge/curation/scripts/limit_tmqm.py, modelforge/dataset/yaml_files/tmqm.yaml
During curation, S was accidentally excluded instead of Se. 
this has been fixed.
=> fixed bug in organic element limiting for tmqm
